################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../source/12_Arial.c \
../source/12_Arial_Bold.c \
../source/14_Arial.c \
../source/14_Arial_Bold.c \
../source/20_Arial.c \
../source/36_Arial.c \
../source/36_bebas.c \
../source/43_Bebas.c \
../source/9_Arial.c \
../source/AKAS_LOGO.c \
../source/Add_Drug.c \
../source/Alarm.c \
../source/Battery.c \
../source/Bebas_60.c \
../source/Bolus_Calculate..c \
../source/Bolus_Screen.c \
../source/Boot_up.c \
../source/Brand.c \
../source/Calibration_Screen.c \
../source/Data_Sample.c \
../source/Device_main_scrn.c \
../source/Dosage_mode.c \
../source/Dose_frame.c \
../source/Dose_mode_fun.c \
../source/Driver_ADC.c \
../source/Driver_HX711.c \
../source/Driver_PINT.c \
../source/Driver_PWM.c \
../source/Driver_SPI.c \
../source/Driver_Timer.c \
../source/Drug_List.c \
../source/Drug_category.c \
../source/Drug_frame.c \
../source/Drug_name_search.c \
../source/Dynamic_pressure.c \
../source/EXTERNAL.RTC.c \
../source/Event_log.c \
../source/Events_log_frames.c \
../source/FR_CALC.c \
../source/Fav_Brand.c \
../source/Fav_drug_list.c \
../source/Flowrate_Screen.c \
../source/Frame_Brand_List.c \
../source/GPIO.c \
../source/I2C.c \
../source/Infused_Calculate.c \
../source/Keypad.c \
../source/Last_infusion.c \
../source/Linear_pot.c \
../source/Linear_pot_functionality.c \
../source/Main_frame.c \
../source/Main_menu.c \
../source/Main_screen_functionality.c \
../source/Motor.c \
../source/Occlusion.c \
../source/Password.c \
../source/Password_screens.c \
../source/Power_off.c \
../source/Pressure_calib.c \
../source/RTC.c \
../source/Ramp_mode.c \
../source/Rec_drug_list.c \
../source/Rec_frame.c \
../source/SD_Calib.c \
../source/SD_Calib_frames.c \
../source/STEPPER.c \
../source/SYR_length_calib.c \
../source/SYR_length_frame.c \
../source/Shapes.c \
../source/Symbol.c \
../source/TFT_Commands.c \
../source/TFT_String.c \
../source/Target_fun.c \
../source/USART.c \
../source/Used_hrs.c \
../source/battery_frames.c \
../source/bolus_limit.c \
../source/bolus_menu_scrn.c \
../source/custom_drug_list.c \
../source/factory_menu.c \
../source/fav_frame.c \
../source/gcov.c \
../source/gcov_support.c \
../source/kvo_menu.c \
../source/main.c \
../source/mode_screen.c \
../source/near_empty.c \
../source/occl_menu.c \
../source/patient_para_sett.c \
../source/plunger_alarm.c \
../source/rtc_driver.c \
../source/semihost_hardfault.c \
../source/serialno_set.c \
../source/sound.c \
../source/standby_fun.c \
../source/sys_sett_menu.c \
../source/year.c 

C_DEPS += \
./source/12_Arial.d \
./source/12_Arial_Bold.d \
./source/14_Arial.d \
./source/14_Arial_Bold.d \
./source/20_Arial.d \
./source/36_Arial.d \
./source/36_bebas.d \
./source/43_Bebas.d \
./source/9_Arial.d \
./source/AKAS_LOGO.d \
./source/Add_Drug.d \
./source/Alarm.d \
./source/Battery.d \
./source/Bebas_60.d \
./source/Bolus_Calculate..d \
./source/Bolus_Screen.d \
./source/Boot_up.d \
./source/Brand.d \
./source/Calibration_Screen.d \
./source/Data_Sample.d \
./source/Device_main_scrn.d \
./source/Dosage_mode.d \
./source/Dose_frame.d \
./source/Dose_mode_fun.d \
./source/Driver_ADC.d \
./source/Driver_HX711.d \
./source/Driver_PINT.d \
./source/Driver_PWM.d \
./source/Driver_SPI.d \
./source/Driver_Timer.d \
./source/Drug_List.d \
./source/Drug_category.d \
./source/Drug_frame.d \
./source/Drug_name_search.d \
./source/Dynamic_pressure.d \
./source/EXTERNAL.RTC.d \
./source/Event_log.d \
./source/Events_log_frames.d \
./source/FR_CALC.d \
./source/Fav_Brand.d \
./source/Fav_drug_list.d \
./source/Flowrate_Screen.d \
./source/Frame_Brand_List.d \
./source/GPIO.d \
./source/I2C.d \
./source/Infused_Calculate.d \
./source/Keypad.d \
./source/Last_infusion.d \
./source/Linear_pot.d \
./source/Linear_pot_functionality.d \
./source/Main_frame.d \
./source/Main_menu.d \
./source/Main_screen_functionality.d \
./source/Motor.d \
./source/Occlusion.d \
./source/Password.d \
./source/Password_screens.d \
./source/Power_off.d \
./source/Pressure_calib.d \
./source/RTC.d \
./source/Ramp_mode.d \
./source/Rec_drug_list.d \
./source/Rec_frame.d \
./source/SD_Calib.d \
./source/SD_Calib_frames.d \
./source/STEPPER.d \
./source/SYR_length_calib.d \
./source/SYR_length_frame.d \
./source/Shapes.d \
./source/Symbol.d \
./source/TFT_Commands.d \
./source/TFT_String.d \
./source/Target_fun.d \
./source/USART.d \
./source/Used_hrs.d \
./source/battery_frames.d \
./source/bolus_limit.d \
./source/bolus_menu_scrn.d \
./source/custom_drug_list.d \
./source/factory_menu.d \
./source/fav_frame.d \
./source/gcov.d \
./source/gcov_support.d \
./source/kvo_menu.d \
./source/main.d \
./source/mode_screen.d \
./source/near_empty.d \
./source/occl_menu.d \
./source/patient_para_sett.d \
./source/plunger_alarm.d \
./source/rtc_driver.d \
./source/semihost_hardfault.d \
./source/serialno_set.d \
./source/sound.d \
./source/standby_fun.d \
./source/sys_sett_menu.d \
./source/year.d 

OBJS += \
./source/12_Arial.o \
./source/12_Arial_Bold.o \
./source/14_Arial.o \
./source/14_Arial_Bold.o \
./source/20_Arial.o \
./source/36_Arial.o \
./source/36_bebas.o \
./source/43_Bebas.o \
./source/9_Arial.o \
./source/AKAS_LOGO.o \
./source/Add_Drug.o \
./source/Alarm.o \
./source/Battery.o \
./source/Bebas_60.o \
./source/Bolus_Calculate..o \
./source/Bolus_Screen.o \
./source/Boot_up.o \
./source/Brand.o \
./source/Calibration_Screen.o \
./source/Data_Sample.o \
./source/Device_main_scrn.o \
./source/Dosage_mode.o \
./source/Dose_frame.o \
./source/Dose_mode_fun.o \
./source/Driver_ADC.o \
./source/Driver_HX711.o \
./source/Driver_PINT.o \
./source/Driver_PWM.o \
./source/Driver_SPI.o \
./source/Driver_Timer.o \
./source/Drug_List.o \
./source/Drug_category.o \
./source/Drug_frame.o \
./source/Drug_name_search.o \
./source/Dynamic_pressure.o \
./source/EXTERNAL.RTC.o \
./source/Event_log.o \
./source/Events_log_frames.o \
./source/FR_CALC.o \
./source/Fav_Brand.o \
./source/Fav_drug_list.o \
./source/Flowrate_Screen.o \
./source/Frame_Brand_List.o \
./source/GPIO.o \
./source/I2C.o \
./source/Infused_Calculate.o \
./source/Keypad.o \
./source/Last_infusion.o \
./source/Linear_pot.o \
./source/Linear_pot_functionality.o \
./source/Main_frame.o \
./source/Main_menu.o \
./source/Main_screen_functionality.o \
./source/Motor.o \
./source/Occlusion.o \
./source/Password.o \
./source/Password_screens.o \
./source/Power_off.o \
./source/Pressure_calib.o \
./source/RTC.o \
./source/Ramp_mode.o \
./source/Rec_drug_list.o \
./source/Rec_frame.o \
./source/SD_Calib.o \
./source/SD_Calib_frames.o \
./source/STEPPER.o \
./source/SYR_length_calib.o \
./source/SYR_length_frame.o \
./source/Shapes.o \
./source/Symbol.o \
./source/TFT_Commands.o \
./source/TFT_String.o \
./source/Target_fun.o \
./source/USART.o \
./source/Used_hrs.o \
./source/battery_frames.o \
./source/bolus_limit.o \
./source/bolus_menu_scrn.o \
./source/custom_drug_list.o \
./source/factory_menu.o \
./source/fav_frame.o \
./source/gcov.o \
./source/gcov_support.o \
./source/kvo_menu.o \
./source/main.o \
./source/mode_screen.o \
./source/near_empty.o \
./source/occl_menu.o \
./source/patient_para_sett.o \
./source/plunger_alarm.o \
./source/rtc_driver.o \
./source/semihost_hardfault.o \
./source/serialno_set.o \
./source/sound.o \
./source/standby_fun.o \
./source/sys_sett_menu.o \
./source/year.o 


# Each subdirectory must supply rules for building sources it contributes
source/%.o: ../source/%.c source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -D__REDLIB__ -DCPU_LPC55S16JBD100 -DCPU_LPC55S16JBD100_cm33 -DSDK_OS_BAREMETAL -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=0 -DPRINTF_FLOAT_ENABLE=1 -DSDK_OS_FREE_RTOS -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"D:\01_Vignesh Babu R\04_Workouts\SP1100\02_APR\29-04-2025\AKAS_1100_Battery_section_completed_SP1100_ver_1.00\source" -I"D:\01_Vignesh Babu R\04_Workouts\SP1100\02_APR\29-04-2025\AKAS_1100_Battery_section_completed_SP1100_ver_1.00\board" -I"D:\01_Vignesh Babu R\04_Workouts\SP1100\02_APR\29-04-2025\AKAS_1100_Battery_section_completed_SP1100_ver_1.00\drivers" -I"D:\01_Vignesh Babu R\04_Workouts\SP1100\02_APR\29-04-2025\AKAS_1100_Battery_section_completed_SP1100_ver_1.00\device" -I"D:\01_Vignesh Babu R\04_Workouts\SP1100\02_APR\29-04-2025\AKAS_1100_Battery_section_completed_SP1100_ver_1.00\CMSIS" -O2 -fno-common -g3 -gdwarf-4 -Wall -c -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -fmacro-prefix-map="$(<D)/"= -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-source

clean-source:
	-$(RM) ./source/12_Arial.d ./source/12_Arial.o ./source/12_Arial_Bold.d ./source/12_Arial_Bold.o ./source/14_Arial.d ./source/14_Arial.o ./source/14_Arial_Bold.d ./source/14_Arial_Bold.o ./source/20_Arial.d ./source/20_Arial.o ./source/36_Arial.d ./source/36_Arial.o ./source/36_bebas.d ./source/36_bebas.o ./source/43_Bebas.d ./source/43_Bebas.o ./source/9_Arial.d ./source/9_Arial.o ./source/AKAS_LOGO.d ./source/AKAS_LOGO.o ./source/Add_Drug.d ./source/Add_Drug.o ./source/Alarm.d ./source/Alarm.o ./source/Battery.d ./source/Battery.o ./source/Bebas_60.d ./source/Bebas_60.o ./source/Bolus_Calculate..d ./source/Bolus_Calculate..o ./source/Bolus_Screen.d ./source/Bolus_Screen.o ./source/Boot_up.d ./source/Boot_up.o ./source/Brand.d ./source/Brand.o ./source/Calibration_Screen.d ./source/Calibration_Screen.o ./source/Data_Sample.d ./source/Data_Sample.o ./source/Device_main_scrn.d ./source/Device_main_scrn.o ./source/Dosage_mode.d ./source/Dosage_mode.o ./source/Dose_frame.d ./source/Dose_frame.o ./source/Dose_mode_fun.d ./source/Dose_mode_fun.o ./source/Driver_ADC.d ./source/Driver_ADC.o ./source/Driver_HX711.d ./source/Driver_HX711.o ./source/Driver_PINT.d ./source/Driver_PINT.o ./source/Driver_PWM.d ./source/Driver_PWM.o ./source/Driver_SPI.d ./source/Driver_SPI.o ./source/Driver_Timer.d ./source/Driver_Timer.o ./source/Drug_List.d ./source/Drug_List.o ./source/Drug_category.d ./source/Drug_category.o ./source/Drug_frame.d ./source/Drug_frame.o ./source/Drug_name_search.d ./source/Drug_name_search.o ./source/Dynamic_pressure.d ./source/Dynamic_pressure.o ./source/EXTERNAL.RTC.d ./source/EXTERNAL.RTC.o ./source/Event_log.d ./source/Event_log.o ./source/Events_log_frames.d ./source/Events_log_frames.o ./source/FR_CALC.d ./source/FR_CALC.o ./source/Fav_Brand.d ./source/Fav_Brand.o ./source/Fav_drug_list.d ./source/Fav_drug_list.o ./source/Flowrate_Screen.d ./source/Flowrate_Screen.o ./source/Frame_Brand_List.d ./source/Frame_Brand_List.o ./source/GPIO.d ./source/GPIO.o ./source/I2C.d ./source/I2C.o ./source/Infused_Calculate.d ./source/Infused_Calculate.o ./source/Keypad.d ./source/Keypad.o ./source/Last_infusion.d ./source/Last_infusion.o ./source/Linear_pot.d ./source/Linear_pot.o ./source/Linear_pot_functionality.d ./source/Linear_pot_functionality.o ./source/Main_frame.d ./source/Main_frame.o ./source/Main_menu.d ./source/Main_menu.o ./source/Main_screen_functionality.d ./source/Main_screen_functionality.o ./source/Motor.d ./source/Motor.o ./source/Occlusion.d ./source/Occlusion.o ./source/Password.d ./source/Password.o ./source/Password_screens.d ./source/Password_screens.o ./source/Power_off.d ./source/Power_off.o ./source/Pressure_calib.d ./source/Pressure_calib.o ./source/RTC.d ./source/RTC.o ./source/Ramp_mode.d ./source/Ramp_mode.o ./source/Rec_drug_list.d ./source/Rec_drug_list.o ./source/Rec_frame.d ./source/Rec_frame.o ./source/SD_Calib.d ./source/SD_Calib.o ./source/SD_Calib_frames.d ./source/SD_Calib_frames.o ./source/STEPPER.d ./source/STEPPER.o ./source/SYR_length_calib.d ./source/SYR_length_calib.o ./source/SYR_length_frame.d ./source/SYR_length_frame.o ./source/Shapes.d ./source/Shapes.o ./source/Symbol.d ./source/Symbol.o ./source/TFT_Commands.d ./source/TFT_Commands.o ./source/TFT_String.d ./source/TFT_String.o ./source/Target_fun.d ./source/Target_fun.o ./source/USART.d ./source/USART.o ./source/Used_hrs.d ./source/Used_hrs.o ./source/battery_frames.d ./source/battery_frames.o ./source/bolus_limit.d ./source/bolus_limit.o ./source/bolus_menu_scrn.d ./source/bolus_menu_scrn.o ./source/custom_drug_list.d ./source/custom_drug_list.o ./source/factory_menu.d ./source/factory_menu.o ./source/fav_frame.d ./source/fav_frame.o ./source/gcov.d ./source/gcov.o ./source/gcov_support.d ./source/gcov_support.o ./source/kvo_menu.d ./source/kvo_menu.o ./source/main.d ./source/main.o ./source/mode_screen.d ./source/mode_screen.o ./source/near_empty.d ./source/near_empty.o ./source/occl_menu.d ./source/occl_menu.o ./source/patient_para_sett.d ./source/patient_para_sett.o ./source/plunger_alarm.d ./source/plunger_alarm.o ./source/rtc_driver.d ./source/rtc_driver.o ./source/semihost_hardfault.d ./source/semihost_hardfault.o ./source/serialno_set.d ./source/serialno_set.o ./source/sound.d ./source/sound.o ./source/standby_fun.d ./source/standby_fun.o ./source/sys_sett_menu.d ./source/sys_sett_menu.o ./source/year.d ./source/year.o

.PHONY: clean-source

